### ISSUE TITLE
Is this wheel malformatted? Or a bug ?

### ISSUE THREAD

**Issue by jcfr** [jcfr/SimpleITKPythonPackage#5]
Commit https://github.com/jcfr/SimpleITKPythonPackage/commit/d16083094ee3d24fed01cf6bee6e87b873c8c848 brings us closer but a last issue remains. See below:

```
+ auditwheel repair dist/SimpleITK-0.10.0-cp27-cp27m-linux_x86_64.whl -w /work/dist/
Repairing SimpleITK-0.10.0-cp27-cp27m-linux_x86_64.whl
Traceback (most recent call last):
  File "/usr/local/bin/auditwheel", line 11, in <module>
    sys.exit(main())
  File "/opt/_internal/cpython-3.5.1/lib/python3.5/site-packages/auditwheel/main.py", line 49, in main
    rval = args.func(args, p)
  File "/opt/_internal/cpython-3.5.1/lib/python3.5/site-packages/auditwheel/main_repair.py", line 81, in execute
    update_tags=args.UPDATE_TAGS)
  File "/opt/_internal/cpython-3.5.1/lib/python3.5/site-packages/auditwheel/repair.py", line 68, in repair_wheel
    raise RuntimeError('Is this wheel malformatted? Or a bug?')
RuntimeError: Is this wheel malformatted? Or a bug?

```

**Comment by jcfr** [comment]
I wonder if [project](https://github.com/SimpleITK/SimpleITKDistribution/blob/578236945fe9e7c165b27031ecebaa2332651b03/manylinux/cmd.sh#L72-L76) of @blowekamp has the same problem.

**Comment by blowekamp** [comment]
I have not seen that error before.

**Comment by jcfr** [comment]
Thanks for the feedback.

After investigating, it turns out the master of auditwheel works as expected. Commit pypa/auditwheel@d92a1c4 fixes the issue.

I am now trying to get a better understanding of the context

**Comment by jcfr** [comment]
Here is the code that was triggering the exception:

```
[...]
        for fn, v in external_refs_by_fn.items():
            # pkg_root should resolve to like numpy/ or scipy/
            # note that it's possible for the wheel to contain
            # more than one pkg, which is why we detect the pkg root
            # for each fn.
            pkg_root = fn.split(os.sep)[0]

            if pkg_root == fn:
                # this file is an extension that's not contained in a
                # directory -- just supposed to be directly in site-packages
                dest_dir = lib_sdir + pkg_root.split('.')[0]
            else:
                if not exists(pjoin(pkg_root, '__init__.py')):
                    raise RuntimeError('Is this wheel malformatted? Or a bug?')
                dest_dir = pjoin(pkg_root, lib_sdir)
[...]
```

with 

```
pkg_root: SimpleITK-0.10.0.data
```

and 

```
$ pwd
/home/jcfr/Projects/SimpleITKPythonPackage/dist/SimpleITK-0.10.0-cp27-cp27mu-linux_x86_64

$ find .
.
./SimpleITK-0.10.0.data
./SimpleITK-0.10.0.data/purelib
./SimpleITK-0.10.0.data/purelib/SimpleITK
./SimpleITK-0.10.0.data/purelib/SimpleITK/ITK-4.10-README.txt
./SimpleITK-0.10.0.data/purelib/SimpleITK/Readme.md
./SimpleITK-0.10.0.data/purelib/SimpleITK/ITK-4.10-NOTICE
./SimpleITK-0.10.0.data/purelib/SimpleITK/NOTICE
./SimpleITK-0.10.0.data/purelib/SimpleITK/SimpleITK.py
./SimpleITK-0.10.0.data/purelib/SimpleITK/__init__.py
./SimpleITK-0.10.0.data/purelib/SimpleITK/_SimpleITK.so
./SimpleITK-0.10.0.data/purelib/SimpleITK/LICENSE
./SimpleITK-0.10.0.dist-info
./SimpleITK-0.10.0.dist-info/top_level.txt
./SimpleITK-0.10.0.dist-info/DESCRIPTION.rst
./SimpleITK-0.10.0.dist-info/WHEEL
./SimpleITK-0.10.0.dist-info/RECORD
./SimpleITK-0.10.0.dist-info/metadata.json
./SimpleITK-0.10.0.dist-info/METADATA
```

**Comment by jcfr** [comment]
```
$ cat SimpleITK-0.10.0.dist-info/WHEEL 
Wheel-Version: 1.0
Generator: bdist_wheel (0.29.0)
Root-Is-Purelib: false
Tag: cp27-cp27mu-linux_x86_64

$ cat SimpleITK-0.10.0.dist-info/top_level.txt 
SimpleITK
```

**Comment by jcfr** [comment]
And the root issue was that wheel generated by `skbuild` where packaging the module under a `SimpleITK-0.10.0.data/purelib` directory.

PR https://github.com/scikit-build/scikit-build/pull/193 fixes the root cause.

All the wheels were properly re-tagged by auditwheel:

```
$ find ./dist/
./dist/
./dist/SimpleITK-0.10.0-cp35-cp35m-manylinux1_x86_64.whl
./dist/SimpleITK-0.10.0-cp33-cp33m-manylinux1_x86_64.whl
./dist/SimpleITK-0.10.0-cp27-cp27mu-manylinux1_x86_64.whl
./dist/SimpleITK-0.10.0-cp34-cp34m-manylinux1_x86_64.whl
./dist/SimpleITK-0.10.0-cp27-cp27m-manylinux1_x86_64.whl
``` 

It is also possible to pip install each one of them and run the following command `import SimpleITK as sitk; print(sitk.Version())`
